version: '3'

services:
  server:
    image: jhonnold/avalon-server:0.1.1
    command: npm start
    ports:
      - 3001:8080

  avalon:
    build:
      context: .
      dockerfile: Dockerfile
    image: avalon
    command: nginx
    environment:
      - NODE_ENV=production
    ports:
      - 3000:80
    depends_on:
      - server
